// * Set Actions
export const BALANCE_SET = "BALANCE_SET";
export const BLOCK_CURRENT_SET = "BLOCK_CURRENT_SET";
export const ENS_ADDRESS_SET = "ENS_ADDRESS_SET";
export const NETWORK_SET = "NETWORK_SET";
export const NONCE_SET = "NONCE_SET";

export const SET_PROVIDER = "SET_PROVIDER";
export const SET_PROVIDER_MULTIPLE = "SET_PROVIDER_MULTIPLE";
export const SET_PROVIDER_STATUS = "SET_PROVIDER_STATUS";

export const SIGNER_GET_REQUEST = "SIGNER_GET_REQUEST";
export const SIGNER_GET_SUCCESS = "SIGNER_GET_SUCCESS";
export const SIGNER_GET_FAILURE = "SIGNER_GET_FAILURE";

export const SET_WALLET = "SET_WALLET";
export const SET_ADDRESS = "SET_ADDRESS";

// export const TRANSACTION_MONITOR_REQUEST = "TRANSACTION_MONITOR_REQUEST";
// export const TRANSACTION_MONITOR_SUCCESS = "TRANSACTION_MONITOR_SUCCESS";
// export const TRANSACTION_MONITOR_FAILURE = "TRANSACTION_MONITOR_FAILURE";
